### ISSUE TITLE
Access to the homeassistant-meteoswiss repo

### ISSUE THREAD

**Issue by naevtamarkus** [websylv/homeassistant-meteoswiss-img#1]
Hi!

I'd like to try your meteoswiss home assistant integration... do you mind making it available to me somehow? I could fork and take it from there.
I know you're not maintaining this anymore, not asking you to do that.

Thanks!

**Comment by websylv** [comment]
i have no time to work on this 
please check : https://github.com/Rudd-O/homeassistant-meteoswiss
